pipeline:
  backend:
    image: node:8.16.0-alpine
    commands:
      - yarn install --ignore-optional
      - yarn test

  # frontend:
  #   image: node:6
  #   commands:
  #     - npm install
  #     - npm test
  # 
  # publish:
  #   image: plugins/docker
  #   repo: octocat/hello-world
  #   tags: [ 1, 1.1, latest ]
  #   registry: index.docker.io
  # 
  # notify:
  #   image: plugins/slack
  #   channel: developers
  #   username: drone