pipeline:
  test:
    image: node:8.16.0-alpine
    commands:
      - yarn install --ignore-optional
      - yarn test
  build:
    image: node:8.16.0-alpine
    commands:
      - yarn install --ignore-optional
      - yarn buildProd

  # frontend:
  #   image: node:6
  #   commands:
  #     - npm install
  #     - npm test
  # 
  publish:
    image: plugins/docker
    settings:
      registry: http://registry:5000
      repo: pokemonjs
      tags: latest
  # 
  # notify:
  #   image: plugins/slack
  #   channel: developers
  #   username: drone