pipeline:
  # test:
  #   image: node:8.16.0-alpine
  #   commands:
  #     - yarn install --ignore-optional
  #     - yarn test

  publish:
    image: plugins/docker
    registry: http://registyui
    password: pa55word
    debug: true
    repo: matehickey/pokemonjs
    username: matehickey
    password: abcde
    tags: droneCI
    # auto_tag: true
    when:
      branch:
        - devtools/droneCI

  # frontend:
  #   image: node:6
  #   commands:
  #     - npm install
  #     - npm test
  #
  #
  # notify:
  #   image: plugins/slack
  #   channel: developers
  #   username: drone
