default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
  <<: *default


test:
  <<: *default
  database: myapp_test
